# Generated by Django 3.1 on 2020-12-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_remove_note_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='file1',
            field=models.FileField(blank=True, upload_to='files'),
        ),
    ]
